// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1WJBmjfSFe_9Land8aHiKoq_s4CLpM_M',
    appId: '1:289942770178:web:4d72700245db138e5f0d1b',
    messagingSenderId: '289942770178',
    projectId: 'ppb-belajar',
    authDomain: 'ppb-belajar.firebaseapp.com',
    storageBucket: 'ppb-belajar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDahHnp5RwPKtE_lNh8R2Lzkaw4Vk9Rt8',
    appId: '1:289942770178:android:f62f69c7d3551b5f5f0d1b',
    messagingSenderId: '289942770178',
    projectId: 'ppb-belajar',
    storageBucket: 'ppb-belajar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGT0dCGekSjZqTN5PllLSuFRTjQKwHX8',
    appId: '1:289942770178:ios:1279143a466e72545f0d1b',
    messagingSenderId: '289942770178',
    projectId: 'ppb-belajar',
    storageBucket: 'ppb-belajar.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnGT0dCGekSjZqTN5PllLSuFRTjQKwHX8',
    appId: '1:289942770178:ios:1279143a466e72545f0d1b',
    messagingSenderId: '289942770178',
    projectId: 'ppb-belajar',
    storageBucket: 'ppb-belajar.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1WJBmjfSFe_9Land8aHiKoq_s4CLpM_M',
    appId: '1:289942770178:web:4ce90394402af2905f0d1b',
    messagingSenderId: '289942770178',
    projectId: 'ppb-belajar',
    authDomain: 'ppb-belajar.firebaseapp.com',
    storageBucket: 'ppb-belajar.firebasestorage.app',
  );

}